### ISSUE TITLE
Error when enabling on Blender 2.81

### ISSUE THREAD

**Issue by Chrisppapples** [lumbermixalot/lumbermixalot#1]
When you install the ZIP it accepts the addon in blender, but when you try to enable it, it gives an issue.

![lumbermixalotissue](https://user-images.githubusercontent.com/58133396/69492436-d9b70e00-0e70-11ea-8160-d34c7eb76f6a.jpg)

**Comment by lumbermixalot** [comment]
It seems Blender 2.81 brought a python API change. Lumbermixalot was developed on Blender 2.80. I'll check on that.
Can you please share the error as text?

**Comment by lumbermixalot** [comment]
I just fixed the bug and updated to version 1.1.1.
Give it a shot.
It seems Blender 2.81 was not lenient anymore about the name of the **bl_description** field. I was using **description**.

**Comment by Chrisppapples** [comment]
Thanks!
